export const domains = [
  "Physical development",
  "Socio-economic, social, emotional development",
  "Cognitive development",
  "Language and literacy development",
  "Aesthetic and cultural development",
  "Positive learning habits"
];

export const curricularGoals = [
  { id: "CG-1", text: "Develops habits that keep them healthy and safe" },
  { id: "CG-2", text: "Develop sharpness and sensorial perceptions" },
  { id: "CG-3", text: "Develops a fit and flexible body" },
  { id: "CG-4", text: "Develops emotional intelligence (that is, the ability to understand and manage their own emotions and respond positively to social norms)" },
  { id: "CG-5", text: "Develops a positive attitude towards productive and productive work and service or seva" },
  { id: "CG-6", text: "Develops a positive regard for the natural environment around them." },
  { id: "CG-7", text: "Makes sense of the world around through observation and logical thinking." },
  { id: "CG-8", text: "Develops mathematical understanding and abilities to recognize the world through quantities, shapes, and measures." },
  { id: "CG-9", text: "Develops effective communication skills for day-to-day Interactions in two languages." },
  { id: "CG-10", text: "develops fluency in reading and writing in language one." },
  { id: "CG-11", text: "begins to read and write in second language." },
  { id: "CG-12", text: "develops abilities and sensibilities in visual and performing arts and expresses their emotions through art in meaningful and joyful ways." },
  { id: "CG-13", text: "develops habits of learning that allow them to engage actively in formal learning environments, such as a school classroom." }
];

export const competencies = [
  { id: "1.1", text: "shows a liking for and understanding of nutritious food and does not waste food." },
  { id: "1.2", text: "practices basic self-care and hygiene." },
  { id: "1.3", text: "keeps cool/classroom hygienic and organized." },
  { id: "1.4", text: "practices safe use of material and simple tools." },
  { id: "1.5", text: "shows awareness of safety in movements (example: walking, running, and cycling), and acts appropriately." },
  { id: "1.6", text: "Understands unsafe situations and asks for help." },
  { id: "2.1", text: "differentiates between shapes, colors, and their shades." },
  { id: "2.2", text: "develops visual memory for symbols and representations." },
  { id: "2.3", text: "differentiates sounds and sound patterns by their pitch, volume, and tempo." },
  { id: "2.4", text: "discriminates multiple smells and tastes" },
  { id: "2.5", text: "Develops discrimination in the sense of smell and taste" },
  { id: "2.6", text: "Develops discrimination in the sense of touch" },
  { id: "3.1", text: "Begins integrating sensorial perceptions to get a holistic awareness of their experiences" },
  { id: "3.2", text: "shows balance, coordination, and flexibility in various physical activities." },
  { id: "3.3", text: "shows precision and control in working with hands and fingers." },
  { id: "3.4", text: "shows strength and endurance in carrying, walking, and running." },
  { id: "4.1", text: "starts recognizing self as an individual belonging to a family and community." },
  { id: "4.2", text: "recognizes different emotions and makes deliberate efforts to regulate them." },
  { id: "4.3", text: "Interacts comfortably with other children and adults" },
  { id: "4.4", text: "Shows cooperative behaviour with other children" },
  { id: "4.5", text: "Understands and responds positively to social norms in the classroom and school" },
  { id: "4.6", text: "Shows kindness and helpfulness to others (including animals, plants) when they are in need" },
  { id: "4.7", text: "Understands and responds positively to different thoughts, preferences, and emotional needs of other children" },
  { id: "5.1", text: "Engages in age-appropriate work at school and/or at home" },
  { id: "6.1", text: "Shows care for and joy in engaging with all life forms" },
  { id: "7.1", text: "Observes and understands different categories of objects and the relationships between them" },
  { id: "7.2", text: "Observes and understands cause and effect relationships in nature by forming simple hypotheses and uses observations to explain their hypotheses" },
  { id: "7.3", text: "Uses appropriate tools and technology in daily life situations and for learning" },
  { id: "8.1", text: "Sorts objects into groups and sub-groups based on more than one property" },
  { id: "8.2", text: "Identifies and extends simple patterns in their surroundings, shapes, and numbers" },
  { id: "8.3", text: "Counts up to 99 both forwards and backwards, and in groups of 5s, 10s, and 20s" },
  { id: "8.4", text: "Arranges numbers up to 99 in ascending and descending order" },
  { id: "8.5", text: "Recognises and uses numerals to represent quantities up to 99 with the understanding of decimal place value system" },
  { id: "8.6", text: "Performs addition and subtraction of 2-digit numbers fluently using flexible strategies of composition and decomposition of both numerical and word problems" },
  { id: "8.7", text: "Recognises multiplication as repeated addition and division as equal sharing" },
  { id: "8.8", text: "Recognises, makes, and classifies basic geometric shapes and their observable properties, and understands and explains the relative relation of objects in space" },
  { id: "8.9", text: "Selects appropriate tools and units to perform simple measurements of length, weight, and volume of objects in their immediate environment" },
  { id: "8.10", text: "Performs simple measurements of time in minutes, hours, day, weeks, and months" },
  { id: "8.11", text: "Performs simple transactions using money up to INR 100" },
  { id: "8.12", text: "Develops adequate and appropriate vocabulary for comprehending and expressing concepts and procedures related to quantities, shapes, space, and measurements" },
  { id: "8.13", text: "Formulates and solves simple mathematical problems related to quantities, shapes, space, and measurements" },
  { id: "8.14", text: "Feels confident and sees Mathematics as doable and worthwhile" },
  { id: "9.1", text: "Listens to and appreciates simple songs, rhymes, and poems" },
  { id: "9.2", text: "Creates simple songs and poems on their own" },
  { id: "9.3", text: "Converses fluently and can hold a meaningful conversation" },
  { id: "9.4", text: "Understands oral instructions for a complex task and gives clear oral instructions for the same to others" },
  { id: "9.5", text: "Comprehends narrated/read-out stories and identifies characters, storyline, and what the author wants to say" },
  { id: "9.6", text: "Narrates short stories with clear plot and characters" },
  { id: "9.7", text: "Knows and uses enough words to carry out day-to-day interactions effectively and can guess the meaning of new words by using existing Vocabulary" },
  { id: "10.1", text: "Develops phonological awareness and blends phonemes/syllables into words and segments words into phonemes/syllables" },
  { id: "10.2", text: "Understands the basic structure/format of a book, idea of words in print and direction in which they are printed, and recognises basic punctuation marks" },
  { id: "10.3", text: "Recognises all the letters of the alphabet (forms of akshara) of the script and uses this knowledge to read and write words" },
  { id: "10.4", text: "Reads stories and passages with accuracy and fluency with appropriate pauses and voice modulation" },
  { id: "10.5", text: "Reads short stories and comprehends their meaning - by identifying characters, storyline and what the author wants to say - on their own" },
  { id: "10.6", text: "Reads short poems and begins to appreciate the poem for its choice of words and imagination" },
  { id: "10.7", text: "Reads and comprehends the meaning of short news items, instructions and recipes, and publicity material" },
  { id: "10.8", text: "Writes a paragraph to express their understanding and experiences" },
  { id: "10.9", text: "Shows interest in picking up and reading a variety of children’s books" },
  { id: "11.1", text: "Develops phonological awareness and is able to blend phonemes/ syllables into words and segment words into phonemes/syllables" },
  { id: "11.2", text: "Recognises most frequently occurring letters of the alphabet (forms of akshara) of the script and uses this knowledge to read and write simple words and sentences" },
  { id: "12.1", text: "Explores and plays with a variety of materials and tools to create two-dimensional and three-dimensional artworks in varying sizes" },
  { id: "12.2", text: "Explores and plays with own voice, body, spaces, and a variety of objects to create Music, role-play, Dance, and Movement" },
  { id: "12.3", text: "Innovates and works imaginatively to express a range of ideas and emotions through the Arts" },
  { id: "12.4", text: "Works collaboratively in the Arts" },
  { id: "12.5", text: "Communicates and appreciates a variety of responses while creating and experiencing different forms of art, local culture, and heritage" },
  { id: "13.1", text: "Attention and intentional action: Acquire skills to plan, focus attention, and direct activities to achieve specific goals" },
  { id: "13.2", text: "Memory and mental flexibility: Develop adequate working memory, mental flexibility (to sustain or shift attention appropriately), and self-control (to resist impulsive actions or responses) that would assist them in learning in structured environments" },
  { id: "13.3", text: "Observation, wonder, curiosity, and exploration: Observes minute details of objects, wonders, and explores using various senses, tinkers with objects, asks questions" },
  { id: "13.4", text: "Classroom norms: Adopts and follows norms with agency and understanding" }
];
